version: "3.1"
# хранилище
volumes:
    pgdata:
        driver: local
services:
    nginx:
# при падении будет стараться подняться
        restart: always
# только свежий nginx
        container_name: nginx
        image: nginx:latest
# слушает порт 8080
        expose:
          - 8080
# мапаем порт 80 на его 8080. Тогда сайт будет доступен по адресу localhost. Убедись, что порт у тебя не занят.
        ports:
          - "80:8080"
# монтируем только те директории, в которых лежит статика, т.к. nginx с динамикой не будет работать. Также директорию с логами и файл настройки, который мы подготовили.
        volumes:
            - ./static:/srv/www/gims-app/static
            - ./media:/srv/www/gims-app/media
            - ./logs:/srv/www/gims-app/logs
            - ./sitename.conf:/etc/nginx/conf.d/sitename.conf
# nginx зависит от контейнера python. Т.е. python должен быть запущен первым
        depends_on:
            - python
    python:
#        restart: always
# указываем откуда собирать образ
#        image: python:latest
        container_name: python
        build:
            context: .
            dockerfile: Dockerfile

## монтируем директорию проекта
        volumes:
            - ./:/srv/www/gims-app
        expose:
          - 8000
        ports:
          - "8000:8000"
# запускаем gunicorn
        command: "gunicorn -c gunicorn.py simple_site_with_tests.wsgi"
    postgres:

        image: postgres:13.15
        ports:
            - "5432:5432"
        container_name: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=postgres
            - POSTGRES_DB=simple_site_with_tests
            - POSTGRES_PORT=5432
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./gims_db.sql:/docker-entrypoint-initdb.d/gims_db.sql
#            - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        depends_on:
            - postgres
        ports:
            - "5051:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: root
        restart: always
