version: "3.1"

volumes:
  pgdata:
    driver: local

services:

  nginx:
    restart: always
    container_name: nginx
    image: nginx:latest
    expose:
      - 8080
    ports:
      - "80:8080"
    volumes:
      - ./static:/srv/www/gims-app/static
      - ./media:/srv/www/gims-app/media
      - ./sitename.conf:/etc/nginx/conf.d/sitename.conf
    depends_on:
      - python

  python:
    restart: always
    container_name: python
    build:
      context: .
    volumes:
      - ./:/srv/www/gims-app
    expose:
      - 8000
    command: "gunicorn -c gunicorn.py simple_site_with_tests.wsgi"
    depends_on:
      - postgres

  postgres:
    image: postgres:13.15
    expose:
      - 5432
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DB=simple_site_with_tests
      - POSTGRES_PORT=5432
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./gims_db.sql:/docker-entrypoint-initdb.d/gims_db.sql
