version: "3.1"

services:

  db:
    restart: always
    image: postgres:13.15
    container_name: demo-postgres #
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DB=simple_site_with_tests
      - POSTGRES_PORT=5432
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./gims_db.sql:/docker-entrypoint-initdb.d/gims_db.sql

  pgadmin:
      image: dpage/pgadmin4
      container_name: demo-pgadmin #you can change this
      depends_on:
        - db
      ports:
        - "5051:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.ru
        PGADMIN_DEFAULT_PASSWORD: admin
      restart: always


volumes:
  postgres_data:
