# Generated by Django 3.1.1 on 2020-09-02 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'test_category',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('answers', models.TextField(blank=True, default='')),
                ('correct_answer', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tests_app.testcategory')),
            ],
        ),
    ]
