# Generated by Django 3.1 on 2020-08-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcategory',
            options={'ordering': ('name',), 'verbose_name': 'test_category'},
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('category', models.ManyToManyField(to='tests_app.TestCategory')),
            ],
        ),
    ]
