# Generated by Django 3.1 on 2020-09-01 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='answers',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='ticket',
            name='correct_answer',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tests_app.testcategory'),
        ),
    ]
