# Generated by Django 3.1.1 on 2020-09-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0002_auto_20200904_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
