# Generated by Django 3.1.1 on 2020-09-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0003_auto_20200904_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='text',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('answers', models.TextField(default='')),
                ('correct_answer', models.TextField(default='')),
                ('ticket', models.ManyToManyField(to='tests_app.Ticket')),
            ],
        ),
    ]
