# Generated by Django 3.1.1 on 2020-09-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0004_auto_20200904_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ticket',
            field=models.ManyToManyField(related_name='questions', to='tests_app.Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='tests_app.testcategory'),
        ),
    ]
