# Generated by Django 3.1.1 on 2020-09-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0005_auto_20200904_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('category', 'slug')},
        ),
    ]
