# Generated by Django 3.1.1 on 2020-09-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0008_auto_20200917_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
    ]
